"""Run script to add collected match data"""

from setup import create_connection
from setup import execute_query

cnx = create_connection(True)

execute_query(cnx, ("INSERT INTO Matches ("
        + "MatchID, RedSideTeam, RedSideTop, RedSideJgl, RedSideMid, RedSideAdc, RedSideSup, BlueSideTeam, BlueSideTop, BlueSideJgl, BlueSideMid, BlueSideAdc, BlueSideSup, WinningTeam) VALUES"
        + "(1, 'SK Gaming', 'Ornn', 'Diana', 'Corki', 'Varus', 'Poppy', 'Fnatic', 'Gnar', 'Zyra', 'Yone', 'Ezreal', 'Rell', 'Fnatic'),"
        + "(2, 'G2 Esports', 'Cho\\'Gath', 'Vi', 'Ahri', 'Ezreal', 'Leona', 'Team Heretics', 'Maokai', 'Wukong', 'Sylas', 'Corki', 'Rakan', 'G2 Esports'),"
        + "(3, 'Karmine Corp', 'Jayce', 'Nidalee', 'Yone', 'Kai\\'Sa', 'Leona', 'Team BDS', 'Ornn', 'Zyra', 'Aurora', 'Ezreal', 'Rell', 'Team BDS'),"
        + "(4, 'Movistar KOI', 'Jayce', 'Sejuani', 'Corki', 'Ziggs', 'Rell', 'Rogue', 'Sion', 'Xin Zhao', 'Viktor', 'Varus', 'Alistar', 'Movistar KOI'),"
        + "(5, 'Team Vitality', 'Jayce', 'Maokai', 'Azir', 'Ezreal', 'Rell', 'GIANTX', 'Sion', 'Zyra', 'Corki', 'Miss Fortune', 'Leona', 'Team Vitality'),"
        + "(6, 'G2 Esports', 'Ornn', 'Wukong', 'Aurora', 'Ezreal', 'Leona', 'Movistar KOI', 'Gwen', 'Vi', 'Taliyah', 'Varus', 'Rakan', 'G2 Esports'),"
        + "(7, 'Team Heretics', 'Jayce', 'Taliyah', 'Smolder', 'Varus', 'Rell', 'Team Vitality', 'Ambessa', 'Zyra', 'Yone', 'Corki', 'Rakan', 'Team Vitality'),"
        + "(8, 'Fnatic', 'Ambessa', 'Vi', 'Aurora', 'Kai\\'Sa', 'Rakan', 'Karmine Corp', 'Poppy', 'Xin Zhao', 'Azir', 'Ezreal', 'Leona', 'Fnatic'),"
        + "(9, 'Team BDS', 'Rumble', 'Maokai', 'Ambessa', 'Varus', 'Leona', 'GIANTX', 'Renekton', 'Nocturne', 'Orianna', 'Kalista', 'Gragas', 'GIANTX'),"
        + "(10, 'Rogue', 'Jayce', 'Sejuani', 'Azir', 'Varus', 'Rell', 'SK Gaming', 'Ornn', 'Wukong', 'Orianna', 'Ezreal', 'Rakan', 'SK Gaming'),"
        + "(11, 'Team Vitality', 'Jayce', 'Wukong', 'Viktor', 'Varus', 'Braum', 'Karmine Corp', 'Ambessa', 'Sejuani', 'Corki', 'Kalista', 'Rell', 'Karmine Corp'),"
        + "(12, 'Team Heretics', 'K\\'Sante', 'Lillia', 'Corki', 'Draven', 'Rell', 'Movistar KOI', 'Ambessa', 'Nidalee', 'Jayce', 'Ezreal', 'Braum', 'Team Heretics'),"
        + "(13, 'Rogue', 'Jayce', 'Maokai', 'Galio', 'Corki', 'Braum', 'G2 Esports', 'Cho\\'Gath', 'Vi', 'Ahri', 'Ezreal', 'Leona', 'G2 Esports'),"
        + "(14, 'GIANTX', 'Jayce', 'Vi', 'Aurora', 'Ezreal', 'Alistar', 'Fnatic', 'Ambessa', 'Maokai', 'Corki', 'Kai\\'Sa', 'Leona', 'Fnatic'),"
        + "(15, 'SK Gaming', 'K^sante', 'Xin Zhao', 'Viktor', 'Ashe', 'Braum', 'Team BDS', 'Rumble', 'Nidalee', 'Jayce', 'Varus', 'Rell', 'Team BDS'),"
        + "(16, 'SK Gaming', 'Jax', 'Sejuani', 'Viktor', 'Ezreal', 'Rakan', 'Movistar KOI', 'Ambessa', 'Vi', 'Hwei', 'Corki', 'Nautilus', 'Movistar KOI'),"
        + "(17, 'Karmine Corp', 'Gnar', 'Xin Zhao', 'Viktor', 'Ezreal', 'Leona', 'Team Heretics', 'Jax', 'Sejuani', 'Hwei', 'Varus', 'Braum', 'Karmine Corp'),"
        + "(18, 'G2 Esports', 'K\\'Sante', 'Zyra', 'Corki', 'Miss Fortune', 'Nautilus', 'GIANTX', 'Jayce', 'Nidalee', 'Smolder', 'Varus', 'Leona', 'G2 Esports'),"
        + "(19, 'Fnatic', 'Rumble', 'Vi', 'Smolder', 'Kalista', 'Rell', 'Team BDS', 'Renekton', 'Nidalee', 'Jayce', 'Varus', 'Braum', 'Fnatic'),"
        + "(20, 'Team Vitality', 'K\\'Sante', 'Wukong', 'Viktor', 'Nilah', 'Rell', 'Rogue', 'Ambessa', 'Vi', 'Galio', 'Varus', 'Rakan', 'Team Vitality'),"
        + "(21, 'Team BDS', 'K\\'Sante', 'Sejuani', 'Viktor', 'Jinx', 'Rell', 'Movistar KOI', 'Ambessa', 'Zyra', 'Yone', 'Ezreal', 'Leona', 'Movistar KOI'),"
        + "(22, 'Karmine Corp', 'Jayce', 'Xin Zhao', 'Viktor', 'Draven', 'Leona', 'Rogue', 'Jax', 'Sejuani', 'Sylas', 'Kalista', 'Rell', 'Karmine Corp'),"
        + "(23, 'Fnatic', 'Jayce', 'Maokai', 'Azir', 'Ezreal', 'Leona', 'G2 Esports', 'Renekton', 'Xin Zhao', 'Sylas', 'Varus', 'Rakan', 'Fnatic'),"
        + "(24, 'SK Gaming', 'Jayce', 'Sejuani', 'Viktor', 'Ezreal', 'Elise', 'Team Vitality', 'Gragas', 'Wukong', 'Azir', 'Varus', 'Braum', 'Team Vitality'),"
        + "(25, 'GIANTX', 'Jayce', 'Vi', 'Azir', 'Varus', 'Rell', 'Team Heretics', 'Ambessa', 'Xin Zhao', 'Viktor', 'Corki', 'Renata Glasc', 'GIANTX'),"
        + "(26, 'Karmine Corp', 'Gragas', 'Zyra', 'Corki', 'Draven', 'Rell', 'SK Gaming', 'Rumble', 'Sejuani', 'Yone', 'Kalista', 'Renata Glasc', 'Karmine Corp'),"
        + "(27, 'Team Vitality', 'Rumble', 'Maokai', 'Corki', 'Jhin', 'Rell', 'G2 Esports', 'K\\'Sante', 'Brand', 'Smolder', 'Varus', 'Alistar', 'G2 Esports'),"
        + "(28, 'GIANTX', 'K\\'Sante', 'Sejuani', 'Akali', 'Ezreal', 'Poppy', 'Movistar KOI', 'Ambessa', 'Vi', 'Taliyah', 'Corki', 'Braum', 'Movistar KOI'),"
        + "(29, 'Team BDS', 'Renekton', 'Sejuani', 'Corki', 'Ezreal', 'Alistar', 'Team Heretics', 'K\\'Sante', 'Zyra', 'Smolder', 'Varus', 'Rell', 'Team Heretics'),"
        + "(30, 'Rogue', 'K\\'Sante', 'Xin Zhao', 'Orianna', 'Varus', 'Rell', 'Fnatic', 'Ambessa', 'Vi', 'Corki', 'Kai\\'Sa', 'Galio', 'Fnatic'),"
        + "(31, 'GIANTX', 'K\\'Sante', 'Sejuani', 'Yone', 'Corki', 'Poppy', 'Karmine Corp', 'Ambessa', 'Vi', 'Taliyah', 'Varus', 'Renata Glasc', 'GIANTX'),"
        + "(32, 'G2 Esports', 'Poppy', 'Xin Zhao', 'Viktor', 'Draven', 'Rell', 'SK Gaming', 'K\\'Sante', 'Nidalee', 'Yone', 'Corki', 'Leona', 'G2 Esports'),"
        + "(33, 'Movistar KOI', 'K\\'Sante', 'Zyra', 'Yone', 'Corki', 'Rell', 'Team Vitality', 'Ambessa', 'Vi', 'Ahri', 'Ezreal', 'Rakan', 'Movistar KOI'),"
        + "(34, 'Team Heretics', 'Renekton', 'Ivern', 'Viktor', 'Corki', 'Leona', 'Fnatic', 'Jayce', 'Maokai', 'Hwei', 'Varus', 'Leona', 'Fnatic'),"
        + "(35, 'Team BDS', 'K\\'Sante', 'Maokai', 'Hwei', 'Corki', 'Rell', 'Rogue', 'Olaf', 'Sejuani', 'Cassiopeia', 'Kalista', 'Leona', 'Team BDS'),"
        + "(36, 'Fnatic', 'Rumble', 'Skarner', 'Yone', 'Ezreal', 'Rell', 'Team Vitality', 'Ambessa', 'Ivern', 'Azir', 'Corki', 'Leona', 'Fnatic'),"
        + "(37, 'G2 Esports', 'Ambessa', 'Vi', 'Sylas', 'Kalista', 'Renata Glasc', 'Team BDS', 'K\\'Sante', 'Sejuani', 'Orianna', 'Varus', 'Seraphine', 'Team BDS'),"
        + "(38, 'Movistar KOI', 'K\\'Sante', 'Xin Zhao', 'Ahri', 'Kalista', 'Renata Glac', 'Karmine Corp', 'Rumble', 'Maokai', 'Corki', 'Varus', 'Rell', 'Karmine Corp'),"
        + "(39, 'Rogue', 'Renekton', 'Sejuani', 'Azir', 'Corki', 'Leona', 'GIANTX', 'Rumble', 'Vi', 'Yone', 'Kai\\'Sa', 'Rell', 'GIANTX'),"
        + "(40, 'Team Heretics', 'Jax', 'Maokai', 'Viktor', 'Ezreal', 'Leona', 'SK Gaming', 'Jayce', 'Xin Zhao', 'Galio', 'Varus', 'Rell', 'Team Heretics'),"
        + "(41, 'Karmine Corp', 'Jayce', 'Sejuani', 'Viktor', 'Ezreal', 'Alistar', 'G2 Esports', 'Gragas', 'Wukong', 'Akali', 'Miss Fortune', 'Rell', 'Karmine Corp'),"
        + "(42, 'Movistar KOI', 'K\\'Sante', 'Skarner', 'Azir', 'Varus', 'Rell', 'Fnatic', 'Jax', 'Ivern', 'Viktor', 'Miss Fortune', 'Alistar' , 'Movistar KOI'),"
        + "(43, 'GIANTX', 'Jax', 'Maokai', 'Viktor', 'Ezreal', 'Rell', 'SK Gaming', 'Jayce', 'Xin Zhao', 'Galio', 'Jinx', 'Braum', 'GIANTX'),"
        + "(44, 'Team Vitality', 'Jax', 'Ivern', 'Taliyah', 'Corki', 'Alistar', 'Team BDS', 'Renekton', 'Sejuani', 'Azir', 'Miss Fortune', 'Rell', 'Team Vitality'),"
        + "(45, 'Team Heretics', 'K\\'Sante', 'Sejuani', 'Viktor', 'Zeri', 'Rell', 'Rogue', 'Garen', 'Maokai', 'Orianna', 'Varus', 'Alistar', 'Rogue')"))