"""Run script to add collected match data"""

from setup import create_connection
from setup import execute_query

if __name__ == "__main__":
  
    cnx = create_connection(True)

    execute_query(cnx, ("INSERT INTO Matches ("
        + "RedSideTeam, RedSideTop, RedSideJgl, RedSideMid, RedSideAdc, RedSideSup, BlueSideTeam, BlueSideTop, BlueSideJgl, BlueSideMid, BlueSideAdc, BlueSideSup, WinningTeam) VALUES"
        + "('SK Gaming', 'Ornn', 'Diana', 'Corki', 'Varus', 'Poppy', 'Fnatic', 'Gnar', 'Zyra', 'Yone', 'Ezreal', 'Rell', 'Fnatic'),"
        + "('G2 Esports', 'Cho\\'Gath', 'Vi', 'Ahri', 'Ezreal', 'Leona', 'Team Heretics', 'Maokai', 'Wukong', 'Sylas', 'Corki', 'Rakan', 'G2 Esports'),"
        + "('Karmine Corp', 'Jayce', 'Nidalee', 'Yone', 'Kai\\'Sa', 'Leona', 'Team BDS', 'Ornn', 'Zyra', 'Aurora', 'Ezreal', 'Rell', 'Team BDS'),"
        + "('Movistar KOI', 'Jayce', 'Sejuani', 'Corki', 'Ziggs', 'Rell', 'Rogue', 'Sion', 'Xin Zhao', 'Viktor', 'Varus', 'Alistar', 'Movistar KOI'),"
        + "('Team Vitality', 'Jayce', 'Maokai', 'Azir', 'Ezreal', 'Rell', 'GIANTX', 'Sion', 'Zyra', 'Corki', 'Miss Fortune', 'Leona', 'Team Vitality'),"
        + "('G2 Esports', 'Ornn', 'Wukong', 'Aurora', 'Ezreal', 'Leona', 'Movistar KOI', 'Gwen', 'Vi', 'Taliyah', 'Varus', 'Rakan', 'G2 Esports'),"
        + "('Team Heretics', 'Jayce', 'Taliyah', 'Smolder', 'Varus', 'Rell', 'Team Vitality', 'Ambessa', 'Zyra', 'Yone', 'Corki', 'Rakan', 'Team Vitality'),"
        + "('Fnatic', 'Ambessa', 'Vi', 'Aurora', 'Kai\\'Sa', 'Rakan', 'Karmine Corp', 'Poppy', 'Xin Zhao', 'Azir', 'Ezreal', 'Leona', 'Fnatic'),"
        + "('Team BDS', 'Rumble', 'Maokai', 'Ambessa', 'Varus', 'Leona', 'GIANTX', 'Renekton', 'Nocturne', 'Orianna', 'Kalista', 'Gragas', 'GIANTX'),"
        + "('Rogue', 'Jayce', 'Sejuani', 'Azir', 'Varus', 'Rell', 'SK Gaming', 'Ornn', 'Wukong', 'Orianna', 'Ezreal', 'Rakan', 'SK Gaming'),"
        + "('Team Vitality', 'Jayce', 'Wukong', 'Viktor', 'Varus', 'Braum', 'Karmine Corp', 'Ambessa', 'Sejuani', 'Corki', 'Kalista', 'Rell', 'Karmine Corp'),"
        + "('Team Heretics', 'K\\'Sante', 'Lillia', 'Corki', 'Draven', 'Rell', 'Movistar KOI', 'Ambessa', 'Nidalee', 'Jayce', 'Ezreal', 'Braum', 'Team Heretics'),"
        + "('Rogue', 'Jayce', 'Maokai', 'Galio', 'Corki', 'Braum', 'G2 Esports', 'Cho\\'Gath', 'Vi', 'Ahri', 'Ezreal', 'Leona', 'G2 Esports'),"
        + "('GIANTX', 'Jayce', 'Vi', 'Aurora', 'Ezreal', 'Alistar', 'Fnatic', 'Ambessa', 'Maokai', 'Corki', 'Kai\\'Sa', 'Leona', 'Fnatic'),"
        + "('SK Gaming', 'K\\'Sante', 'Xin Zhao', 'Viktor', 'Ashe', 'Braum', 'Team BDS', 'Rumble', 'Nidalee', 'Jayce', 'Varus', 'Rell', 'Team BDS'),"
        + "('SK Gaming', 'Jax', 'Sejuani', 'Viktor', 'Ezreal', 'Rakan', 'Movistar KOI', 'Ambessa', 'Vi', 'Hwei', 'Corki', 'Nautilus', 'Movistar KOI'),"
        + "('Karmine Corp', 'Gnar', 'Xin Zhao', 'Viktor', 'Ezreal', 'Leona', 'Team Heretics', 'Jax', 'Sejuani', 'Hwei', 'Varus', 'Braum', 'Karmine Corp'),"
        + "('G2 Esports', 'K\\'Sante', 'Zyra', 'Corki', 'Miss Fortune', 'Nautilus', 'GIANTX', 'Jayce', 'Nidalee', 'Smolder', 'Varus', 'Leona', 'G2 Esports'),"
        + "('Fnatic', 'Rumble', 'Vi', 'Smolder', 'Kalista', 'Rell', 'Team BDS', 'Renekton', 'Nidalee', 'Jayce', 'Varus', 'Braum', 'Fnatic'),"
        + "('Team Vitality', 'K\\'Sante', 'Wukong', 'Viktor', 'Nilah', 'Rell', 'Rogue', 'Ambessa', 'Vi', 'Galio', 'Varus', 'Rakan', 'Team Vitality'),"
        + "('Team BDS', 'K\\'Sante', 'Sejuani', 'Viktor', 'Jinx', 'Rell', 'Movistar KOI', 'Ambessa', 'Zyra', 'Yone', 'Ezreal', 'Leona', 'Movistar KOI'),"
        + "('Karmine Corp', 'Jayce', 'Xin Zhao', 'Viktor', 'Draven', 'Leona', 'Rogue', 'Jax', 'Sejuani', 'Sylas', 'Kalista', 'Rell', 'Karmine Corp'),"
        + "('Fnatic', 'Jayce', 'Maokai', 'Azir', 'Ezreal', 'Leona', 'G2 Esports', 'Renekton', 'Xin Zhao', 'Sylas', 'Varus', 'Rakan', 'Fnatic'),"
        + "('SK Gaming', 'Jayce', 'Sejuani', 'Viktor', 'Ezreal', 'Elise', 'Team Vitality', 'Gragas', 'Wukong', 'Azir', 'Varus', 'Braum', 'Team Vitality'),"
        + "('GIANTX', 'Jayce', 'Vi', 'Azir', 'Varus', 'Rell', 'Team Heretics', 'Ambessa', 'Xin Zhao', 'Viktor', 'Corki', 'Renata Glasc', 'GIANTX'),"
        + "('Karmine Corp', 'Gragas', 'Zyra', 'Corki', 'Draven', 'Rell', 'SK Gaming', 'Rumble', 'Sejuani', 'Yone', 'Kalista', 'Renata Glasc', 'Karmine Corp'),"
        + "('Team Vitality', 'Rumble', 'Maokai', 'Corki', 'Jhin', 'Rell', 'G2 Esports', 'K\\'Sante', 'Brand', 'Smolder', 'Varus', 'Alistar', 'G2 Esports'),"
        + "('GIANTX', 'K\\'Sante', 'Sejuani', 'Akali', 'Ezreal', 'Poppy', 'Movistar KOI', 'Ambessa', 'Vi', 'Taliyah', 'Corki', 'Braum', 'Movistar KOI'),"
        + "('Team BDS', 'Renekton', 'Sejuani', 'Corki', 'Ezreal', 'Alistar', 'Team Heretics', 'K\\'Sante', 'Zyra', 'Smolder', 'Varus', 'Rell', 'Team Heretics'),"
        + "('Rogue', 'K\\'Sante', 'Xin Zhao', 'Orianna', 'Varus', 'Rell', 'Fnatic', 'Ambessa', 'Vi', 'Corki', 'Kai\\'Sa', 'Galio', 'Fnatic'),"
        + "('GIANTX', 'K\\'Sante', 'Sejuani', 'Yone', 'Corki', 'Poppy', 'Karmine Corp', 'Ambessa', 'Vi', 'Taliyah', 'Varus', 'Renata Glasc', 'GIANTX'),"
        + "('G2 Esports', 'Poppy', 'Xin Zhao', 'Viktor', 'Draven', 'Rell', 'SK Gaming', 'K\\'Sante', 'Nidalee', 'Yone', 'Corki', 'Leona', 'G2 Esports'),"
        + "('Movistar KOI', 'K\\'Sante', 'Zyra', 'Yone', 'Corki', 'Rell', 'Team Vitality', 'Ambessa', 'Vi', 'Ahri', 'Ezreal', 'Rakan', 'Movistar KOI'),"
        + "('Team Heretics', 'Renekton', 'Ivern', 'Viktor', 'Corki', 'Leona', 'Fnatic', 'Jayce', 'Maokai', 'Hwei', 'Varus', 'Leona', 'Fnatic'),"
        + "('Team BDS', 'K\\'Sante', 'Maokai', 'Hwei', 'Corki', 'Rell', 'Rogue', 'Olaf', 'Sejuani', 'Cassiopeia', 'Kalista', 'Leona', 'Team BDS'),"
        + "('Fnatic', 'Rumble', 'Skarner', 'Yone', 'Ezreal', 'Rell', 'Team Vitality', 'Ambessa', 'Ivern', 'Azir', 'Corki', 'Leona', 'Fnatic'),"
        + "('G2 Esports', 'Ambessa', 'Vi', 'Sylas', 'Kalista', 'Renata Glasc', 'Team BDS', 'K\\'Sante', 'Sejuani', 'Orianna', 'Varus', 'Seraphine', 'Team BDS'),"
        + "('Movistar KOI', 'K\\'Sante', 'Xin Zhao', 'Ahri', 'Kalista', 'Renata Glasc', 'Karmine Corp', 'Rumble', 'Maokai', 'Corki', 'Varus', 'Rell', 'Karmine Corp'),"
        + "('Rogue', 'Renekton', 'Sejuani', 'Azir', 'Corki', 'Leona', 'GIANTX', 'Rumble', 'Vi', 'Yone', 'Kai\\'Sa', 'Rell', 'GIANTX'),"
        + "('Team Heretics', 'Jax', 'Maokai', 'Viktor', 'Ezreal', 'Leona', 'SK Gaming', 'Jayce', 'Xin Zhao', 'Galio', 'Varus', 'Rell', 'Team Heretics'),"
        + "('Karmine Corp', 'Jayce', 'Sejuani', 'Viktor', 'Ezreal', 'Alistar', 'G2 Esports', 'Gragas', 'Wukong', 'Akali', 'Miss Fortune', 'Rell', 'Karmine Corp'),"
        + "('Movistar KOI', 'K\\'Sante', 'Skarner', 'Azir', 'Varus', 'Rell', 'Fnatic', 'Jax', 'Ivern', 'Viktor', 'Miss Fortune', 'Alistar' , 'Movistar KOI'),"
        + "('GIANTX', 'Jax', 'Maokai', 'Viktor', 'Ezreal', 'Rell', 'SK Gaming', 'Jayce', 'Xin Zhao', 'Galio', 'Jinx', 'Braum', 'GIANTX'),"
        + "('Team Vitality', 'Jax', 'Ivern', 'Taliyah', 'Corki', 'Alistar', 'Team BDS', 'Renekton', 'Sejuani', 'Azir', 'Miss Fortune', 'Rell', 'Team Vitality'),"
        + "('Team Heretics', 'K\\'Sante', 'Sejuani', 'Viktor', 'Zeri', 'Rell', 'Rogue', 'Garen', 'Maokai', 'Orianna', 'Varus', 'Alistar', 'Rogue')"))
